// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDexvzTDIce-NWVAGEJ7rbAcdUInUspqfc',
    appId: '1:277795486640:web:76e45e58acc0d6a628f475',
    messagingSenderId: '277795486640',
    projectId: 'indonesia-stays',
    authDomain: 'indonesia-stays.firebaseapp.com',
    storageBucket: 'indonesia-stays.firebasestorage.app',
    measurementId: 'G-3DRZ78F3PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRwOyPifI5Um3aBkxB337J01zLZU2x-BI',
    appId: '1:277795486640:android:3ef6f2c5f004a0bc28f475',
    messagingSenderId: '277795486640',
    projectId: 'indonesia-stays',
    storageBucket: 'indonesia-stays.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV5EQr-SdbAU7B-s7bwkxhsK4RrYZBU9A',
    appId: '1:277795486640:ios:f3d9e9920cbd121d28f475',
    messagingSenderId: '277795486640',
    projectId: 'indonesia-stays',
    storageBucket: 'indonesia-stays.firebasestorage.app',
    iosBundleId: 'com.example.realEstateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV5EQr-SdbAU7B-s7bwkxhsK4RrYZBU9A',
    appId: '1:277795486640:ios:f3d9e9920cbd121d28f475',
    messagingSenderId: '277795486640',
    projectId: 'indonesia-stays',
    storageBucket: 'indonesia-stays.firebasestorage.app',
    iosBundleId: 'com.example.realEstateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDexvzTDIce-NWVAGEJ7rbAcdUInUspqfc',
    appId: '1:277795486640:web:9fb4af26a5ada1f228f475',
    messagingSenderId: '277795486640',
    projectId: 'indonesia-stays',
    authDomain: 'indonesia-stays.firebaseapp.com',
    storageBucket: 'indonesia-stays.firebasestorage.app',
    measurementId: 'G-CBMM5Q0LWH',
  );
}
